name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies for the frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend/podeo-web-app/podeo-web-app
        run: npm install

      # Step 4: Build the Angular frontend
      - name: Build Frontend
        working-directory: ./frontend/podeo-web-app/podeo-web-app
        run: npm run build --prod

      # Step 5: Build Docker image for frontend
      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      # Step 6: Install dependencies for the backend
      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install

      # Step 7: Build Docker image for backend
      - name: Build Backend Docker Image
        working-directory: ./server
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      # Step 8: Log in to Docker Hub
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 9: Push Docker images
      - name: Push Frontend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      - name: Push Backend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest